PRAGMA foreign_keys=ON;

DROP TABLE IF EXISTS game_request;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
    username TEXT PRIMARY KEY,
    password TEXT NOT NULL,
    victories INTEGER NOT NULL DEFAULT 0,
    games INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE game_request (
    game TEXT PRIMARY KEY,
    seeds INTEGER NOT NULL,
    cavs INTEGER NOT NULL,
    user REFERENCES user ON DELETE CASCADE ON UPDATE CASCADE,
    match BOOLEAN NOT NULL DEFAULT FALSE
);

